/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ldroid_kwei_ndkdemo_Ndk */

#ifndef _Included_com_ldroid_kwei_ndkdemo_Ndk
#define _Included_com_ldroid_kwei_ndkdemo_Ndk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ldroid_kwei_ndkdemo_Ndk
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ldroid_kwei_ndkdemo_Ndk_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
